// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "scam-detection-backend/internal/models"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), user)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockUserRepository) GetAll(limit, offset int) ([]models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, offset)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserRepositoryMockRecorder) GetAll(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserRepository)(nil).GetAll), limit, offset)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(id uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), id)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), username)
}

// GetByUsernameOrEmail mocks base method.
func (m *MockUserRepository) GetByUsernameOrEmail(login string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsernameOrEmail", login)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsernameOrEmail indicates an expected call of GetByUsernameOrEmail.
func (mr *MockUserRepositoryMockRecorder) GetByUsernameOrEmail(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsernameOrEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByUsernameOrEmail), login)
}

// Update mocks base method.
func (m *MockUserRepository) Update(id uint, data *models.UpdateUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), id, data)
}

// UpdateActiveStatus mocks base method.
func (m *MockUserRepository) UpdateActiveStatus(id uint, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActiveStatus", id, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActiveStatus indicates an expected call of UpdateActiveStatus.
func (mr *MockUserRepositoryMockRecorder) UpdateActiveStatus(id, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActiveStatus", reflect.TypeOf((*MockUserRepository)(nil).UpdateActiveStatus), id, isActive)
}

// UpdateRole mocks base method.
func (m *MockUserRepository) UpdateRole(id uint, role models.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", id, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockUserRepositoryMockRecorder) UpdateRole(id, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockUserRepository)(nil).UpdateRole), id, role)
}

// MockCheckRepository is a mock of CheckRepository interface.
type MockCheckRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckRepositoryMockRecorder
}

// MockCheckRepositoryMockRecorder is the mock recorder for MockCheckRepository.
type MockCheckRepositoryMockRecorder struct {
	mock *MockCheckRepository
}

// NewMockCheckRepository creates a new mock instance.
func NewMockCheckRepository(ctrl *gomock.Controller) *MockCheckRepository {
	mock := &MockCheckRepository{ctrl: ctrl}
	mock.recorder = &MockCheckRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckRepository) EXPECT() *MockCheckRepositoryMockRecorder {
	return m.recorder
}

// AddCheckDetail mocks base method.
func (m *MockCheckRepository) AddCheckDetail(detail *models.CheckDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCheckDetail", detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCheckDetail indicates an expected call of AddCheckDetail.
func (mr *MockCheckRepositoryMockRecorder) AddCheckDetail(detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCheckDetail", reflect.TypeOf((*MockCheckRepository)(nil).AddCheckDetail), detail)
}

// CreateCheck mocks base method.
func (m *MockCheckRepository) CreateCheck(check *models.Check) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheck", check)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCheck indicates an expected call of CreateCheck.
func (mr *MockCheckRepositoryMockRecorder) CreateCheck(check interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheck", reflect.TypeOf((*MockCheckRepository)(nil).CreateCheck), check)
}

// DeleteCheck mocks base method.
func (m *MockCheckRepository) DeleteCheck(id, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCheck", id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCheck indicates an expected call of DeleteCheck.
func (mr *MockCheckRepositoryMockRecorder) DeleteCheck(id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCheck", reflect.TypeOf((*MockCheckRepository)(nil).DeleteCheck), id, userID)
}

// GetAllChecks mocks base method.
func (m *MockCheckRepository) GetAllChecks(limit, offset int) ([]models.Check, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllChecks", limit, offset)
	ret0, _ := ret[0].([]models.Check)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllChecks indicates an expected call of GetAllChecks.
func (mr *MockCheckRepositoryMockRecorder) GetAllChecks(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllChecks", reflect.TypeOf((*MockCheckRepository)(nil).GetAllChecks), limit, offset)
}

// GetCheckByID mocks base method.
func (m *MockCheckRepository) GetCheckByID(id uint) (*models.Check, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckByID", id)
	ret0, _ := ret[0].(*models.Check)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckByID indicates an expected call of GetCheckByID.
func (mr *MockCheckRepositoryMockRecorder) GetCheckByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckByID", reflect.TypeOf((*MockCheckRepository)(nil).GetCheckByID), id)
}

// GetCheckDetails mocks base method.
func (m *MockCheckRepository) GetCheckDetails(checkID uint) ([]models.CheckDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckDetails", checkID)
	ret0, _ := ret[0].([]models.CheckDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckDetails indicates an expected call of GetCheckDetails.
func (mr *MockCheckRepositoryMockRecorder) GetCheckDetails(checkID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckDetails", reflect.TypeOf((*MockCheckRepository)(nil).GetCheckDetails), checkID)
}

// GetChecksByUserID mocks base method.
func (m *MockCheckRepository) GetChecksByUserID(userID uint, limit, offset int) ([]models.Check, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecksByUserID", userID, limit, offset)
	ret0, _ := ret[0].([]models.Check)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetChecksByUserID indicates an expected call of GetChecksByUserID.
func (mr *MockCheckRepositoryMockRecorder) GetChecksByUserID(userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecksByUserID", reflect.TypeOf((*MockCheckRepository)(nil).GetChecksByUserID), userID, limit, offset)
}

// GetGlobalStats mocks base method.
func (m *MockCheckRepository) GetGlobalStats() (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalStats")
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalStats indicates an expected call of GetGlobalStats.
func (mr *MockCheckRepositoryMockRecorder) GetGlobalStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalStats", reflect.TypeOf((*MockCheckRepository)(nil).GetGlobalStats))
}

// GetUserStats mocks base method.
func (m *MockCheckRepository) GetUserStats(userID uint) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStats", userID)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStats indicates an expected call of GetUserStats.
func (mr *MockCheckRepositoryMockRecorder) GetUserStats(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStats", reflect.TypeOf((*MockCheckRepository)(nil).GetUserStats), userID)
}

// UpdateCheckStatus mocks base method.
func (m *MockCheckRepository) UpdateCheckStatus(id uint, status string, dangerScore float64, dangerLevel string, processingTime int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCheckStatus", id, status, dangerScore, dangerLevel, processingTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCheckStatus indicates an expected call of UpdateCheckStatus.
func (mr *MockCheckRepositoryMockRecorder) UpdateCheckStatus(id, status, dangerScore, dangerLevel, processingTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCheckStatus", reflect.TypeOf((*MockCheckRepository)(nil).UpdateCheckStatus), id, status, dangerScore, dangerLevel, processingTime)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, s *models.UserSessions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, s)
}

// DeleteExpired mocks base method.
func (m *MockSessionRepository) DeleteExpired(ctx context.Context, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockSessionRepositoryMockRecorder) DeleteExpired(ctx, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockSessionRepository)(nil).DeleteExpired), ctx, now)
}

// GetActiveByHash mocks base method.
func (m *MockSessionRepository) GetActiveByHash(ctx context.Context, hash string, now time.Time) (*models.UserSessions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByHash", ctx, hash, now)
	ret0, _ := ret[0].(*models.UserSessions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByHash indicates an expected call of GetActiveByHash.
func (mr *MockSessionRepositoryMockRecorder) GetActiveByHash(ctx, hash, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByHash", reflect.TypeOf((*MockSessionRepository)(nil).GetActiveByHash), ctx, hash, now)
}

// InvalidateAllByUser mocks base method.
func (m *MockSessionRepository) InvalidateAllByUser(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAllByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAllByUser indicates an expected call of InvalidateAllByUser.
func (mr *MockSessionRepositoryMockRecorder) InvalidateAllByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAllByUser", reflect.TypeOf((*MockSessionRepository)(nil).InvalidateAllByUser), ctx, userID)
}

// MarkUsed mocks base method.
func (m *MockSessionRepository) MarkUsed(ctx context.Context, id uint, usedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, id, usedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockSessionRepositoryMockRecorder) MarkUsed(ctx, id, usedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockSessionRepository)(nil).MarkUsed), ctx, id, usedAt)
}
